/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'sf-pro': ['var(--font-sans)'],
        'mono': ['var(--font-mono)'],
      },
      colors: {
        severity: {
          critical: {
            50: 'var(--severity-critical-50)',
            100: 'var(--severity-critical-100)',
            200: 'var(--severity-critical-200)',
            300: 'var(--severity-critical-300)',
            400: 'var(--severity-critical-400)',
            500: 'var(--severity-critical-500)',
            600: 'var(--severity-critical-600)',
            700: 'var(--severity-critical-700)',
            800: 'var(--severity-critical-800)',
            900: 'var(--severity-critical-900)',
          },
          high: {
            50: 'var(--severity-high-50)',
            100: 'var(--severity-high-100)',
            200: 'var(--severity-high-200)',
            300: 'var(--severity-high-300)',
            400: 'var(--severity-high-400)',
            500: 'var(--severity-high-500)',
            600: 'var(--severity-high-600)',
            700: 'var(--severity-high-700)',
            800: 'var(--severity-high-800)',
            900: 'var(--severity-high-900)',
          },
          medium: {
            50: 'var(--severity-medium-50)',
            100: 'var(--severity-medium-100)',
            200: 'var(--severity-medium-200)',
            300: 'var(--severity-medium-300)',
            400: 'var(--severity-medium-400)',
            500: 'var(--severity-medium-500)',
            600: 'var(--severity-medium-600)',
            700: 'var(--severity-medium-700)',
            800: 'var(--severity-medium-800)',
            900: 'var(--severity-medium-900)',
          },
          low: {
            50: 'var(--severity-low-50)',
            100: 'var(--severity-low-100)',
            200: 'var(--severity-low-200)',
            300: 'var(--severity-low-300)',
            400: 'var(--severity-low-400)',
            500: 'var(--severity-low-500)',
            600: 'var(--severity-low-600)',
            700: 'var(--severity-low-700)',
            800: 'var(--severity-low-800)',
            900: 'var(--severity-low-900)',
          },
          compliant: {
            50: 'var(--severity-compliant-50)',
            100: 'var(--severity-compliant-100)',
            200: 'var(--severity-compliant-200)',
            300: 'var(--severity-compliant-300)',
            400: 'var(--severity-compliant-400)',
            500: 'var(--severity-compliant-500)',
            600: 'var(--severity-compliant-600)',
            700: 'var(--severity-compliant-700)',
            800: 'var(--severity-compliant-800)',
            900: 'var(--severity-compliant-900)',
          },
        },
        primary: {
          50: 'var(--primary-50)',
          100: 'var(--primary-100)',
          200: 'var(--primary-200)',
          300: 'var(--primary-300)',
          400: 'var(--primary-400)',
          500: 'var(--primary-500)',
          600: 'var(--primary-600)',
          700: 'var(--primary-700)',
          800: 'var(--primary-800)',
          900: 'var(--primary-900)',
        },
        psychotropic: {
          50: 'var(--severity-low-50)',
          100: 'var(--severity-low-100)',
          200: 'var(--severity-low-200)',
          500: 'var(--severity-low-500)',
          600: 'var(--severity-low-600)',
          700: 'var(--severity-low-700)',
        },
        catheter: {
          50: 'var(--severity-compliant-50)',
          100: 'var(--severity-compliant-100)',
          200: 'var(--severity-compliant-200)',
          500: 'var(--severity-compliant-500)',
          600: 'var(--severity-compliant-600)',
          700: 'var(--severity-compliant-700)',
        },
        skinwound: {
          50: 'var(--severity-high-50)',
          100: 'var(--severity-high-100)',
          200: 'var(--severity-high-200)',
          500: 'var(--severity-high-500)',
          600: 'var(--severity-high-600)',
          700: 'var(--severity-high-700)',
        },
        success: {
          50: 'var(--severity-compliant-50)',
          200: 'var(--severity-compliant-200)',
          500: 'var(--severity-compliant-500)',
          700: 'var(--severity-compliant-700)',
        },
        warning: {
          50: 'var(--severity-medium-50)',
          200: 'var(--severity-medium-200)',
          500: 'var(--severity-medium-500)',
          700: 'var(--severity-medium-700)',
        },
        error: {
          50: 'var(--severity-critical-50)',
          200: 'var(--severity-critical-200)',
          500: 'var(--severity-critical-500)',
          700: 'var(--severity-critical-700)',
        },
      },
      spacing: {
        '0': 'var(--space-0)',
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
        '24': 'var(--space-24)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'DEFAULT': 'var(--shadow-base)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'apple': 'var(--shadow-lg)',
        'apple-hover': 'var(--shadow-xl)',
      },
      borderRadius: {
        'sm': 'var(--radius-sm)',
        'DEFAULT': 'var(--radius-base)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
        'apple': 'var(--radius-base)',
        'apple-lg': 'var(--radius-lg)',
      },
      transitionDuration: {
        'fast': '150ms',
        'DEFAULT': '250ms',
        'slow': '350ms',
      },
      transitionTimingFunction: {
        'DEFAULT': 'var(--ease-in-out)',
        'spring': 'var(--ease-spring)',
      },
    },
  },
  plugins: [],
}
